plugins {
    id "architectury-plugin" version "3.5-SNAPSHOT"
    id "dev.architectury.loom-no-remap" version "1.17-SNAPSHOT" apply false
    id "com.gradleup.shadow" version "9.6.1" apply false
}

architectury {
    minecraft = rootProject.minecraft_version
}

subprojects {
    apply plugin: "dev.architectury.loom-no-remap"

    dependencies {
        minecraft "com.mojang:minecraft:${rootProject.minecraft_version}"
    }
}

allprojects {
    apply plugin: "java"
    apply plugin: "architectury-plugin"

    version = rootProject.mod_version
    group = rootProject.maven_group

    repositories {
        maven { url "https://maven.fabricmc.net/" }
        maven { url "https://maven.architectury.dev/" }
        maven { url "https://maven.neoforged.net/releases/" }
        maven { url "https://maven.fzzyhmstrs.me/" }
        maven { url "https://maven.terraformersmc.com/releases/" }
        maven { url "https://thedarkcolour.github.io/KotlinForForge/" }
        mavenCentral()
    }

    tasks.withType(JavaCompile).configureEach {
        options.encoding = "UTF-8"
        options.release = 25
    }

    java {
        withSourcesJar()
    }
}
