architectury {
    common(rootProject.enabled_platforms.split(","))
}

base {
    archivesName = rootProject.archives_base_name + "-common"
}

sourceSets {
    main {
        resources {
            srcDir "src/generated/resources"
            exclude ".cache/**"
        }
    }
}

dependencies {
    implementation "net.fabricmc:fabric-loader:${rootProject.fabric_loader_version}"
    compileOnly "net.fabricmc.fabric-api:fabric-api:${rootProject.fabric_api_version}"
    api "dev.architectury:architectury:${rootProject.architectury_version}"
    api "me.fzzyhmstrs:fzzy_config:${rootProject.fzzy_config_version}"
}
